recipes.remove(<appliedenergistics2:item.ItemMultiPart:160>);
recipes.remove(<appliedenergistics2:item.ItemMultiPart:180>);
recipes.remove(<appliedenergistics2:item.ItemMultiPart:35>);
recipes.remove(<appliedenergistics2:item.ItemMultiPart:16>);
recipes.remove(<appliedenergistics2:tile.BlockInterface>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:43>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:44>);
recipes.remove(<appliedenergistics2:tile.BlockEnergyCell>);
recipes.remove(<extracells:storage.casing:2>);
recipes.remove(<extracells:storage.casing:1>);
recipes.remove(<extracells:storage.casing>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:39>);
recipes.remove(<extracells:storage.gas:6>);
recipes.remove(<extracells:storage.gas:5>);
recipes.remove(<extracells:storage.gas:4>);
recipes.remove(<extracells:storage.gas:3>);
recipes.remove(<extracells:storage.gas:2>);
recipes.remove(<extracells:storage.gas:1>);
recipes.remove(<extracells:storage.gas>);
recipes.remove(<extracells:storage.fluid:6>);
recipes.remove(<extracells:storage.fluid:5>);
recipes.remove(<extracells:storage.fluid:4>);
recipes.remove(<extracells:storage.fluid:3>);
recipes.remove(<extracells:storage.fluid:2>);
recipes.remove(<extracells:storage.fluid:1>);
recipes.remove(<extracells:storage.fluid>);
recipes.remove(<extracells:storage.physical:3>);
recipes.remove(<extracells:storage.physical:2>);
recipes.remove(<extracells:storage.physical:1>);
recipes.remove(<extracells:storage.physical>);
recipes.remove(<appliedenergistics2:item.ItemBasicStorageCell.64k>);
recipes.remove(<appliedenergistics2:item.ItemBasicStorageCell.16k>);
recipes.remove(<appliedenergistics2:item.ItemBasicStorageCell.4k>);
recipes.remove(<appliedenergistics2:item.ItemBasicStorageCell.1k>);
recipes.remove(<extracells:storage.component:17>);
recipes.remove(<extracells:storage.component:16>);
recipes.remove(<extracells:storage.component:15>);
recipes.remove(<extracells:storage.component:14>);
recipes.remove(<extracells:storage.component:13>);
recipes.remove(<extracells:storage.component:12>);
recipes.remove(<extracells:storage.component:11>);
recipes.remove(<extracells:storage.component:10>);
recipes.remove(<extracells:storage.component:9>);
recipes.remove(<extracells:storage.component:8>);
recipes.remove(<extracells:storage.component:7>);
recipes.remove(<extracells:storage.component:6>);
recipes.remove(<extracells:storage.component:5>);
recipes.remove(<extracells:storage.component:4>);
recipes.remove(<extracells:storage.component:3>);
recipes.remove(<extracells:storage.component:2>);
recipes.remove(<extracells:storage.component:1>);
recipes.remove(<extracells:storage.component>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:38>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:37>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:36>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:35>);
recipes.remove(<appliedenergistics2:tile.BlockMolecularAssembler>);
recipes.remove(<appliedenergistics2:tile.BlockCraftingUnit>);
recipes.remove(<appliedenergistics2:tile.BlockEnergyAcceptor>);
recipes.remove(<appliedenergistics2:tile.BlockChest>);
recipes.remove(<appliedenergistics2:tile.BlockDrive>);
recipes.remove(<appliedenergistics2:tile.BlockController>);
recipes.remove(<appliedenergistics2:tile.BlockQuantumLinkChamber>);
recipes.remove(<appliedenergistics2:tile.BlockQuantumRing>);
recipes.remove(<appliedenergistics2:tile.BlockCharger>);
recipes.remove(<appliedenergistics2:tile.BlockInscriber>);


recipes.addShaped(<appliedenergistics2:item.ItemMultiPart:180>, [[null, <ore:ingotIron>, <ore:paneGlassColorless>], [<appliedenergistics2:item.ItemMultiPart:16>, <ImmersiveEngineering:metalDevice2:3>, <ore:paneGlassColorless>], [null, <ore:ingotIron>, <ore:paneGlassColorless>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiPart:180>, [[<ore:itemIlluminatedPanel>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiPart:160>, [[<ore:itemIlluminatedPanel>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiPart:35> * 4, [[<minecraft:paper>, <appliedenergistics2:item.ItemMultiPart:16>, <minecraft:paper>], [<appliedenergistics2:item.ItemMultiPart:16>, <minecraft:wool>, <appliedenergistics2:item.ItemMultiPart:16>], [<minecraft:paper>, <appliedenergistics2:item.ItemMultiPart:16>, <minecraft:paper>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiPart:16> * 4, [[<ore:cropLapender>, <ore:cropLapender>, <ore:cropLapender>], [<minecraft:redstone>, <appliedenergistics2:item.ItemMultiPart:140>, <ore:dustRedstone>], [<ore:cropLapender>, <ore:cropLapender>, <ore:cropLapender>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockInterface>, [[<appliedenergistics2:item.ItemMultiPart:440>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockInterface>, [[null, <ore:plateSteel>, null], [<appliedenergistics2:item.ItemMultiMaterial:43>, <ore:oc:microcontrollerCase2>, <appliedenergistics2:item.ItemMultiMaterial:44>], [null, <ore:plateSteel>, null]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:44>, [[null, <ore:nuggetIron>, null], [<EnderIO:itemMaterial:4>, <OpenComputers:item:25>, <ThermalFoundation:material:108>], [null, <ore:nuggetIron>, null]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:43>, [[null, <ore:nuggetIron>, null], [<ThermalFoundation:material:106>, <OpenComputers:item:25>, <EnderIO:itemMaterial:4>], [null, <ore:nuggetIron>, null]]);
recipes.addShaped(<appliedenergistics2:tile.BlockEnergyCell>, [[<ore:crystalCertusQuartz>, <ore:ingotIron>, <ore:crystalCertusQuartz>], [<ore:ingotIron>, <EnderIO:blockCapBank:1>, <ore:ingotIron>], [<ore:crystalCertusQuartz>, <minecraft:iron_ingot>, <ore:crystalCertusQuartz>]]);
recipes.addShaped(<extracells:storage.physical:3>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPartIridium>, <extracells:storage.component:3>, <IC2:itemPartIridium>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.physical:2>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPartIridium>, <extracells:storage.component:2>, <IC2:itemPartIridium>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.physical:1>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPartIridium>, <extracells:storage.component:1>, <IC2:itemPartIridium>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.physical>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPartIridium>, <extracells:storage.component>, <IC2:itemPartIridium>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<appliedenergistics2:item.ItemBasicStorageCell.64k>, [[null, <ore:paneGlassColorless>, null], [<ore:plateSteel>, <appliedenergistics2:item.ItemMultiMaterial:38>, <ore:plateSteel>], [null, <ore:oc:componentBus1>, <ore:oc:server1>]]);
recipes.addShaped(<appliedenergistics2:item.ItemBasicStorageCell.16k>, [[null, <ore:paneGlassColorless>, null], [<ore:plateSteel>, <appliedenergistics2:item.ItemMultiMaterial:37>, <ore:plateSteel>], [null, <ore:oc:componentBus1>, <ore:oc:server1>]]);
recipes.addShaped(<appliedenergistics2:item.ItemBasicStorageCell.4k>, [[null, <ore:paneGlassColorless>, null], [<ore:plateSteel>, <appliedenergistics2:item.ItemMultiMaterial:36>, <ore:plateSteel>], [null, <ore:oc:componentBus1>, <ore:oc:server1>]]);
recipes.addShaped(<appliedenergistics2:item.ItemBasicStorageCell.1k>, [[null, <ore:paneGlassColorless>, null], [<ore:plateSteel>, <appliedenergistics2:item.ItemMultiMaterial:35>, <ore:plateSteel>], [null, <ore:oc:componentBus1>, <ore:oc:server1>]]);
recipes.addShaped(<extracells:storage.fluid:6>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, <extracells:storage.component:10>, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.fluid:5>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, <extracells:storage.component:9>, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.fluid:4>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, <extracells:storage.component:8>, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.fluid:3>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, <extracells:storage.component:7>, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.fluid:2>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, <extracells:storage.component:6>, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.fluid:1>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, <extracells:storage.component:5>, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.fluid>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, <extracells:storage.component:4>, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.gas:6>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, <extracells:storage.component:17>, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.gas:5>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, <extracells:storage.component:16>, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.gas:4>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, <extracells:storage.component:15>, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.gas:3>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, <extracells:storage.component:14>, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.gas:2>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, <extracells:storage.component:13>, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.gas:1>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, <extracells:storage.component:12>, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.gas>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, <extracells:storage.component:11>, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.casing:2>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPlates:3>, null, <IC2:itemPlates:3>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.casing:1>, [[null, <ore:paneGlassColorless>, null], [<ImmersiveEngineering:metal:32>, null, <ImmersiveEngineering:metal:32>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<extracells:storage.casing>, [[null, <ore:paneGlassColorless>, null], [<IC2:itemPartIridium>, null, <IC2:itemPartIridium>], [null, <ore:oc:componentBus2>, <ore:oc:server2>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:39>, [[null, <ore:paneGlassColorless>, null], [<ore:plateSteel>, null, <ore:plateSteel>], [null, <ore:oc:componentBus1>, <ore:oc:server1>]]);
recipes.addShaped(<extracells:storage.component:17>, [[<ore:oc:ram5>, <extracells:storage.component:16>, <ore:oc:ram5>], [<extracells:storage.component:16>, <OpenComputers:item:43>, <extracells:storage.component:16>], [<ore:oc:ram5>, <extracells:storage.component:16>, <ore:oc:ram5>]]);
recipes.addShaped(<extracells:storage.component:16>, [[<ore:oc:ram3>, <extracells:storage.component:15>, <ore:oc:ram3>], [<extracells:storage.component:15>, <OpenComputers:item:42>, <extracells:storage.component:15>], [<ore:oc:ram3>, <extracells:storage.component:15>, <ore:oc:ram3>]]);
recipes.addShaped(<extracells:storage.component:15>, [[<ore:oc:ram1>, <extracells:storage.component:14>, <ore:oc:ram1>], [<extracells:storage.component:14>, <OpenComputers:item:29>, <extracells:storage.component:14>], [<ore:oc:ram1>, <extracells:storage.component:14>, <ore:oc:ram1>]]);
recipes.addShaped(<extracells:storage.component:14>, [[<ore:oc:circuitChip3>, <extracells:storage.component:13>, <ore:oc:circuitChip3>], [<extracells:storage.component:13>, <appliedenergistics2:item.ItemMultiMaterial:24>, <extracells:storage.component:13>], [<ore:oc:circuitChip3>, <extracells:storage.component:13>, <ore:oc:circuitChip3>]]);
recipes.addShaped(<extracells:storage.component:13>, [[<ore:oc:circuitChip2>, <extracells:storage.component:12>, <ore:oc:circuitChip2>], [<extracells:storage.component:12>, <appliedenergistics2:item.ItemMultiMaterial:23>, <extracells:storage.component:12>], [<ore:oc:circuitChip2>, <extracells:storage.component:12>, <ore:oc:circuitChip2>]]);
recipes.addShaped(<extracells:storage.component:12>, [[<ore:oc:circuitChip1>, <extracells:storage.component:11>, <ore:oc:circuitChip1>], [<extracells:storage.component:11>, <appliedenergistics2:item.ItemMultiMaterial:22>, <extracells:storage.component:11>], [<ore:oc:circuitChip1>, <extracells:storage.component:11>, <ore:oc:circuitChip1>]]);
recipes.addShaped(<extracells:storage.component:11>, [[null, <ore:oc:circuitChip1>, null], [<ore:oc:circuitChip1>, <Thaumcraft:ItemEssence>, <ore:oc:circuitChip1>], [null, <ore:oc:circuitChip1>, null]]);
recipes.addShaped(<extracells:storage.component:10>, [[<ore:oc:ram5>, <extracells:storage.component:9>, <ore:oc:ram5>], [<extracells:storage.component:9>, <OpenComputers:item:43>, <extracells:storage.component:9>], [<ore:oc:ram5>, <extracells:storage.component:9>, <ore:oc:ram5>]]);
recipes.addShaped(<extracells:storage.component:9>, [[<ore:oc:ram3>, <extracells:storage.component:8>, <ore:oc:ram3>], [<extracells:storage.component:8>, <OpenComputers:item:42>, <extracells:storage.component:8>], [<ore:oc:ram3>, <extracells:storage.component:8>, <ore:oc:ram3>]]);
recipes.addShaped(<extracells:storage.component:8>, [[<ore:oc:ram1>, <extracells:storage.component:7>, <ore:oc:ram1>], [<extracells:storage.component:7>, <OpenComputers:item:29>, <extracells:storage.component:7>], [<ore:oc:ram1>, <extracells:storage.component:7>, <ore:oc:ram1>]]);
recipes.addShaped(<extracells:storage.component:7>, [[<ore:oc:circuitChip3>, <extracells:storage.component:6>, <ore:oc:circuitChip3>], [<extracells:storage.component:6>, <appliedenergistics2:item.ItemMultiMaterial:24>, <extracells:storage.component:6>], [<ore:oc:circuitChip3>, <extracells:storage.component:6>, <ore:oc:circuitChip3>]]);
recipes.addShaped(<extracells:storage.component:6>, [[<ore:oc:circuitChip2>, <extracells:storage.component:5>, <ore:oc:circuitChip2>], [<extracells:storage.component:5>, <appliedenergistics2:item.ItemMultiMaterial:23>, <extracells:storage.component:5>], [<ore:oc:circuitChip2>, <extracells:storage.component:5>, <ore:oc:circuitChip2>]]);
recipes.addShaped(<extracells:storage.component:5>, [[<ore:oc:circuitChip1>, <extracells:storage.component:4>, <ore:oc:circuitChip1>], [<extracells:storage.component:4>, <appliedenergistics2:item.ItemMultiMaterial:22>, <extracells:storage.component:4>], [<ore:oc:circuitChip1>, <extracells:storage.component:4>, <ore:oc:circuitChip1>]]);
recipes.addShaped(<extracells:storage.component:4>, [[null, <OpenComputers:item:24>, null], [<ore:oc:circuitChip1>, <minecraft:glass_bottle>, <OpenComputers:item:24>], [null, <ore:oc:circuitChip1>, null]]);
recipes.addShaped(<extracells:storage.component:3>, [[<ore:oc:ram6>, <extracells:storage.component:2>, <ore:oc:ram6>], [<extracells:storage.component:2>, <OpenComputers:item:102>, <extracells:storage.component:2>], [<ore:oc:ram6>, <extracells:storage.component:2>, <ore:oc:ram6>]]);
recipes.addShaped(<extracells:storage.component:2>, [[<ore:oc:ram5>, <extracells:storage.component:1>, <ore:oc:ram5>], [<extracells:storage.component:1>, <OpenComputers:item:43>, <extracells:storage.component:1>], [<ore:oc:ram5>, <extracells:storage.component:1>, <ore:oc:ram5>]]);
recipes.addShaped(<extracells:storage.component:1>, [[<ore:oc:ram3>, <extracells:storage.component>, <ore:oc:ram3>], [<extracells:storage.component>, <OpenComputers:item:42>, <extracells:storage.component>], [<ore:oc:ram3>, <extracells:storage.component>, <ore:oc:ram3>]]);
recipes.addShaped(<extracells:storage.component>, [[<ore:oc:ram1>, <appliedenergistics2:item.ItemMultiMaterial:38>, <ore:oc:ram1>], [<appliedenergistics2:item.ItemMultiMaterial:38>, <OpenComputers:item:29>, <appliedenergistics2:item.ItemMultiMaterial:38>], [<ore:oc:ram1>, <appliedenergistics2:item.ItemMultiMaterial:38>, <ore:oc:ram1>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:38>, [[<ore:oc:circuitChip3>, <appliedenergistics2:item.ItemMultiMaterial:37>, <ore:oc:circuitChip3>], [<appliedenergistics2:item.ItemMultiMaterial:37>, <appliedenergistics2:item.ItemMultiMaterial:24>, <appliedenergistics2:item.ItemMultiMaterial:37>], [<ore:oc:circuitChip3>, <appliedenergistics2:item.ItemMultiMaterial:37>, <ore:oc:circuitChip3>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:37>, [[<ore:oc:circuitChip2>, <appliedenergistics2:item.ItemMultiMaterial:36>, <ore:oc:circuitChip2>], [<appliedenergistics2:item.ItemMultiMaterial:36>, <appliedenergistics2:item.ItemMultiMaterial:23>, <appliedenergistics2:item.ItemMultiMaterial:36>], [<ore:oc:circuitChip2>, <appliedenergistics2:item.ItemMultiMaterial:36>, <ore:oc:circuitChip2>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:36>, [[<ore:oc:circuitChip1>, <appliedenergistics2:item.ItemMultiMaterial:35>, <ore:oc:circuitChip1>], [<appliedenergistics2:item.ItemMultiMaterial:35>, <appliedenergistics2:item.ItemMultiMaterial:22>, <appliedenergistics2:item.ItemMultiMaterial:35>], [<ore:oc:circuitChip1>, <appliedenergistics2:item.ItemMultiMaterial:35>, <ore:oc:circuitChip1>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:35>, [[null, <ore:oc:circuitChip1>, null], [<ore:oc:circuitChip1>, <ore:crystalCertusQuartz>, <ore:oc:circuitChip1>], [null, <ore:oc:circuitChip1>, null]]);
recipes.addShaped(<appliedenergistics2:tile.BlockQuantumLinkChamber>, [[<academy-craft:ac_Item_calcChip>, <appliedenergistics2:tile.BlockQuartzLamp>, <academy-craft:ac_Item_dataChip>], [<appliedenergistics2:tile.BlockQuartzLamp>, <ThermalExpansion:Frame:11>, <appliedenergistics2:tile.BlockQuartzLamp>], [<academy-craft:ac_Item_dataChip>, <appliedenergistics2:tile.BlockQuartzLamp>, <academy-craft:ac_Item_calcChip>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockQuantumRing>, [[<minecraft:stained_hardened_clay:15>, <OpenComputers:item:43>, <minecraft:stained_hardened_clay:15>], [<ImmersiveEngineering:storage:10>, <appliedenergistics2:item.ItemMultiPart:76>, <ImmersiveEngineering:storage:10>], [<minecraft:stained_hardened_clay:15>, <IC2:blockMachine2:1>, <minecraft:stained_hardened_clay:15>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockChest>, [[<ore:oc:cpu2>, <appliedenergistics2:item.ItemMultiPart:380>, <ore:oc:cpu2>], [<ore:plateSteel>, <IronChest:BlockIronChest:2>, <ore:plateSteel>], [<ore:plateSteel>, <appliedenergistics2:tile.BlockEnergyAcceptor>, <ore:plateSteel>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockController>, [[<ore:compressedMeteoricIron>, <ore:oc:cpu3>, <ore:compressedMeteoricIron>], [<ore:oc:cpu3>, <appliedenergistics2:tile.BlockEnergyAcceptor>, <ore:oc:cpu3>], [<ore:compressedMeteoricIron>, <ore:oc:cpu3>, <ore:compressedMeteoricIron>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockInscriber>, [[<ore:plateSteel>, <ore:componentServo>, <ore:plateSteel>], [null, <minecraft:heavy_weighted_pressure_plate>, <ore:plateSteel>], [<ore:plateSteel>, <ore:componentServo>, <ore:plateSteel>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockCharger>, [[<ore:plateSteel>, <IC2:itemBatLamaCrystal:26>.anyDamage(), <ore:plateSteel>], [null, <ImmersiveEngineering:metalDevice2:10>, <ore:ingotSteel>], [<ore:plateSteel>, <appliedenergistics2:item.ItemMultiPart:16>, <ore:plateSteel>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockDrive>, [[<ore:plateSteel>, <ore:oc:circuitChip3>, <ore:plateSteel>], [<ore:plateSteel>, <IronChest:BlockIronChest:2>, <ore:plateSteel>], [<ore:plateSteel>, <ore:oc:cpu1>, <ore:plateSteel>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockEnergyAcceptor>, [[<ore:plateIron>, <appliedenergistics2:item.ItemMultiPart:16>, <ore:plateIron>], [<appliedenergistics2:item.ItemMultiPart:16>, <ThermalExpansion:Frame:9>, <appliedenergistics2:item.ItemMultiPart:16>], [<ore:plateIron>, <appliedenergistics2:item.ItemMultiPart:16>, <ore:plateIron>]]);
