recipes.remove(<DefenseTech:explosives:12>);
recipes.remove(<DefenseTech:explosives:12>);
recipes.remove(<DefenseTech:explosives:12>);
recipes.remove(<DefenseTech:explosives:12>);
recipes.remove(<DefenseTech:missile:24>);
recipes.remove(<DefenseTech:missile:24>);
recipes.remove(<DefenseTech:missile:24>);
recipes.remove(<DefenseTech:missile:16>);
recipes.remove(<DefenseTech:missile:16>);
recipes.remove(<DefenseTech:missile:16>);
recipes.remove(<DefenseTech:missile:25>);
recipes.remove(<DefenseTech:missile:25>);
recipes.remove(<DefenseTech:missile:25>);
recipes.remove(<DefenseTech:missile:27>);
recipes.remove(<DefenseTech:missile:27>);
recipes.remove(<DefenseTech:missile:27>);
recipes.remove(<DefenseTech:missile:15>);
recipes.remove(<DefenseTech:missile:15>);
recipes.remove(<DefenseTech:missile:15>);
recipes.remove(<DefenseTech:missile:15>);


recipes.removeShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.removeShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.removeShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.removeShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.removeShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.removeShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.removeShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.removeShaped(<DefenseTech:missile:4>, [[<DefenseTech:poisonPowder>, <ExtraUtilities:spike_base_diamond>, <DefenseTech:poisonPowder>], [<DefenseTech:poisonPowder>, <DefenseTech:missile:23>, <DefenseTech:poisonPowder>], [<minecraft:tnt>, <DefenseTech:missile:26>, <minecraft:tnt>]]);
recipes.removeShaped(<DefenseTech:missile:2>, [[<TConstruct:materials:7>, <minecraft:tnt>, <TConstruct:materials:7>], [<minecraft:tnt>, <DefenseTech:missile:4>, <minecraft:tnt>], [<TConstruct:materials:7>, <minecraft:tnt>, <TConstruct:materials:7>]]);
recipes.removeShaped(<DefenseTech:missile:27>, [[<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>], [<powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>], [<GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]]);
recipes.removeShaped(<DefenseTech:missile:27>, [[<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>], [<powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>], [<GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]]);
recipes.removeShaped(<DefenseTech:missile:23>, [[<Mekanism:ControlCircuit:3>, <GalacticraftCore:item.basicItem:19>, <OpenComputers:item:26>], [<IC2:itemPartCircuitAdv>, <powersuits:powerArmorComponent:19>, <IC2:itemPartCircuitAdv>], [<GalacticraftCore:item.rocketFins>, <GalacticraftCore:item.engine>, <GalacticraftCore:item.rocketFins>]]);
recipes.removeShaped(<DefenseTech:missile:23>, [[<Mekanism:ControlCircuit:3>, <GalacticraftCore:item.basicItem:19>, <OpenComputers:item:26>], [<IC2:itemPartCircuitAdv>, <powersuits:powerArmorComponent:19>, <IC2:itemPartCircuitAdv>], [<GalacticraftCore:item.rocketFins>, <GalacticraftCore:item.engine>, <GalacticraftCore:item.rocketFins>]]);
recipes.removeShaped(<DefenseTech:missile>, [[<minecraft:tnt>, <minecraft:tnt>, <IC2:blockITNT>], [<minecraft:tnt>, <DefenseTech:missile:23>, <IC2:blockITNT>], [<minecraft:tnt>, <Mekanism:ControlCircuit:3>, <IC2:blockITNT>]]);
recipes.removeShaped(<DefenseTech:missile>, [[<minecraft:tnt>, <minecraft:tnt>, <IC2:blockITNT>], [<minecraft:tnt>, <DefenseTech:missile:23>, <IC2:blockITNT>], [<minecraft:tnt>, <Mekanism:ControlCircuit:3>, <IC2:blockITNT>]]);
recipes.removeShaped(<DefenseTech:missile:26>, [[<minecraft:tnt>, <IC2:blockITNT>, <minecraft:tnt>], [<IC2:blockITNT>, <DefenseTech:missile:2>, <IC2:blockITNT>], [<minecraft:tnt>, <IC2:blockITNT>, <minecraft:tnt>]]);
recipes.removeShaped(<DefenseTech:missile:26>, [[<minecraft:tnt>, <IC2:blockITNT>, <minecraft:tnt>], [<IC2:blockITNT>, <DefenseTech:missile:2>, <IC2:blockITNT>], [<minecraft:tnt>, <IC2:blockITNT>, <minecraft:tnt>]]);
recipes.addShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.addShapeless(<DefenseTech:missile:27>, [<DefenseTech:missile:15>, <DefenseTech:missile:15>, <DefenseTech:missile:15>, <powersuits:powerArmorComponent:19>, <IC2:itemPlutonium>, <OpenComputers:item:26>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>, <GalacticraftMars:item.itemBasicAsteroids:1>]);
recipes.addShaped(<DefenseTech:missile:4>, [[<DefenseTech:poisonPowder>, <ExtraUtilities:spike_base_diamond>, <DefenseTech:poisonPowder>], [<DefenseTech:poisonPowder>, <DefenseTech:missile:23>, <DefenseTech:poisonPowder>], [<minecraft:tnt>, <DefenseTech:missile:26>, <minecraft:tnt>]]);
recipes.addShaped(<DefenseTech:missile:4>, [[<DefenseTech:poisonPowder>, <ExtraUtilities:spike_base_diamond>, <DefenseTech:poisonPowder>], [<DefenseTech:poisonPowder>, <DefenseTech:missile:23>, <DefenseTech:poisonPowder>], [<minecraft:tnt>, <DefenseTech:missile:26>, <minecraft:tnt>]]);
recipes.addShaped(<DefenseTech:missile:2>, [[<TConstruct:materials:7>, <minecraft:tnt>, <TConstruct:materials:7>], [<minecraft:tnt>, <DefenseTech:missile:4>, <minecraft:tnt>], [<TConstruct:materials:7>, <minecraft:tnt>, <TConstruct:materials:7>]]);
recipes.addShaped(<DefenseTech:missile:24>, [[<powersuits:powerArmorComponent:19>, <IC2:itemPartCircuitAdv>, <powersuits:powerArmorComponent:19>], [<IC2:itemPartCircuitAdv>, <DefenseTech:missile>, <IC2:itemPartCircuitAdv>], [<minecraft:tnt>, <IC2:itemPartCircuitAdv>, <minecraft:tnt>]]);
recipes.addShaped(<DefenseTech:missile:16>, [[<ThermalExpansion:material:2>, <IC2:itemPartCircuitAdv>, <ThermalExpansion:material:2>], [<Mekanism:ControlCircuit:3>, <ThermalExpansion:Frame:9>, <Mekanism:ControlCircuit:3>], [<powersuits:powerArmorComponent:19>, <DefenseTech:missile:23>, <powersuits:powerArmorComponent:19>]]);
recipes.addShaped(<DefenseTech:missile:25>, [[<minecraft:tnt>, <ExtraUtilities:spike_base_diamond>, <minecraft:tnt>], [<Mekanism:ControlCircuit:3>, <DefenseTech:missile:24>, <Mekanism:ControlCircuit:3>], [<GalacticraftCore:item.rocketFins>, <OpenComputers:item:26>, <GalacticraftCore:item.rocketFins>]]);
recipes.addShaped(<DefenseTech:missile:23>, [[<Mekanism:ControlCircuit:3>, <GalacticraftCore:item.basicItem:19>, <OpenComputers:item:26>], [<IC2:itemPartCircuitAdv>, <powersuits:powerArmorComponent:19>, <IC2:itemPartCircuitAdv>], [<GalacticraftCore:item.rocketFins>, <GalacticraftCore:item.engine>, <GalacticraftCore:item.rocketFins>]]);
recipes.addShaped(<DefenseTech:missile>, [[<minecraft:tnt>, <minecraft:tnt>, <IC2:blockITNT>], [<minecraft:tnt>, <DefenseTech:missile:23>, <IC2:blockITNT>], [<minecraft:tnt>, <Mekanism:ControlCircuit:3>, <IC2:blockITNT>]]);
recipes.addShaped(<DefenseTech:missile:26>, [[<minecraft:tnt>, <IC2:blockITNT>, <minecraft:tnt>], [<IC2:blockITNT>, <DefenseTech:missile:2>, <IC2:blockITNT>], [<minecraft:tnt>, <IC2:blockITNT>, <minecraft:tnt>]]);
recipes.addShaped(<DefenseTech:missile:13>, [[<DefenseTech:missile:26>, <IC2:itemPartCircuitAdv>, <DefenseTech:missile:26>], [<IC2:itemPartCircuitAdv>, <IC2:blockITNT>, <IC2:itemPartCircuitAdv>], [<DefenseTech:missile:26>, <IC2:itemPartCircuitAdv>, <DefenseTech:missile:26>]]);
recipes.addShaped(<DefenseTech:missile:13>, [[<DefenseTech:missile:26>, <IC2:itemPartCircuitAdv>, <DefenseTech:missile:26>], [<IC2:itemPartCircuitAdv>, <IC2:blockITNT>, <IC2:itemPartCircuitAdv>], [<DefenseTech:missile:26>, <IC2:itemPartCircuitAdv>, <DefenseTech:missile:26>]]);
recipes.addShaped(<DefenseTech:missile:15>, [[<NuclearCraft:material:36>, <IC2:itemPlutonium>, <NuclearCraft:material:36>], [<IC2:itemPlutonium>, <DefenseTech:missile:13>, <IC2:itemPlutonium>], [<NuclearCraft:material:36>, <IC2:itemPlutonium>, <NuclearCraft:material:36>]]);
