recipes.remove(<ExtraUtilities:enderQuarry>);
recipes.remove(<ExtraUtilities:enderThermicPump>);
recipes.remove(<ExtraUtilities:decorativeBlock1:1>);
recipes.remove(<ExtraUtilities:endConstructor:2>);
recipes.remove(<ExtraUtilities:endConstructor>);
recipes.remove(<ExtraUtilities:decorativeBlock1:11>);
recipes.remove(<ExtraUtilities:filing:1>);
recipes.remove(<ExtraUtilities:filing>);
recipes.remove(<ExtraUtilities:extractor_base:6>);
recipes.remove(<ExtraUtilities:extractor_base>);
recipes.remove(<ExtraUtilities:enderCollector>);
recipes.remove(<ExtraUtilities:watering_can:3>);
recipes.remove(<ExtraUtilities:generator.64:7>);
recipes.remove(<ExtraUtilities:generator.64:6>);
recipes.remove(<ExtraUtilities:generator.64:5>);
recipes.remove(<ExtraUtilities:generator.64:4>);
recipes.remove(<ExtraUtilities:generator.64:3>);
recipes.remove(<ExtraUtilities:generator.64:2>);
recipes.remove(<ExtraUtilities:generator.64:1>);
recipes.remove(<ExtraUtilities:generator.64>);
recipes.remove(<ExtraUtilities:generator.8:11>);
recipes.remove(<ExtraUtilities:generator.8:10>);
recipes.remove(<ExtraUtilities:generator.8:9>);
recipes.remove(<ExtraUtilities:generator.8:8>);
recipes.remove(<ExtraUtilities:generator.8:7>);
recipes.remove(<ExtraUtilities:generator.8:6>);
recipes.remove(<ExtraUtilities:generator.8:5>);
recipes.remove(<ExtraUtilities:generator.8:4>);
recipes.remove(<ExtraUtilities:generator.8:3>);
recipes.remove(<ExtraUtilities:generator.8:2>);
recipes.remove(<ExtraUtilities:generator.8:1>);
recipes.remove(<ExtraUtilities:generator.8>);
recipes.remove(<ExtraUtilities:generator.8>);
recipes.remove(<ExtraUtilities:generator:11>);
recipes.remove(<ExtraUtilities:generator:10>);
recipes.remove(<ExtraUtilities:generator:9>);
recipes.remove(<ExtraUtilities:generator:8>);
recipes.remove(<ExtraUtilities:generator:7>);
recipes.remove(<ExtraUtilities:generator:6>);
recipes.remove(<ExtraUtilities:generator:5>);
recipes.remove(<ExtraUtilities:generator:4>);
recipes.remove(<ExtraUtilities:generator:3>);
recipes.remove(<ExtraUtilities:generator:2>);
recipes.remove(<ExtraUtilities:generator:1>);
recipes.remove(<ExtraUtilities:generator>);
recipes.remove(<ExtraUtilities:generator.64:11>);
recipes.remove(<ExtraUtilities:generator.64:10>);
recipes.remove(<ExtraUtilities:generator.64:8>);
recipes.removeShaped(<ExtraUtilities:angelRing:4>);
recipes.removeShaped(<ExtraUtilities:angelRing:3>);
recipes.removeShaped(<ExtraUtilities:angelRing:2>);
recipes.removeShaped(<ExtraUtilities:angelRing:1>);
recipes.removeShaped(<ExtraUtilities:angelRing>);
recipes.removeShaped(<IC2:itemPartCircuitAdv>);
recipes.remove(<OpenBlocks:fan>);

mods.extraUtils.QED.addShapedRecipe(<ExtraUtilities:enderQuarry>, [[<ore:blockEnderCore>, <appliedenergistics2:item.ItemMultiMaterial:47>, <ore:blockEnderCore>], [<ExtraUtilities:decorativeBlock1:12>, <ThermalExpansion:Tesseract>, <ExtraUtilities:decorativeBlock1:12>], [<ore:blockEnderCore>, <ExtraUtilities:enderThermicPump>, <ExtraUtilities:decorativeBlock1:11>]]);

recipes.addShaped(<ExtraUtilities:endConstructor:2>, [[null, <minecraft:ender_eye>, null], [<ExtraUtilities:decorativeBlock1:12>, <ThermalExpansion:Dynamo:4>, <ExtraUtilities:decorativeBlock1:12>], [<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>]]);
recipes.addShaped(<ExtraUtilities:endConstructor>, [[<ore:blockEnderObsidian>, <minecraft:beacon>, <ore:blockEnderObsidian>], [<ExtraUtilities:decorativeBlock1:12>, <ProjRed|Expansion:projectred.expansion.machine2:11>, <ExtraUtilities:decorativeBlock1:12>], [<ore:blockEnderObsidian>, <ThermalExpansion:Frame:9>, <ore:blockEnderObsidian>]]);
recipes.addShaped(<ExtraUtilities:decorativeBlock1:11>, [[<ore:ingotGold>, <ore:blockEnderObsidian>, <ore:ingotGold>], [<ore:blockEnderObsidian>, <minecraft:ender_eye>, <ExtraUtilities:decorativeBlock1:1>], [<ore:ingotGold>, <ExtraUtilities:decorativeBlock1:1>, <ore:ingotGold>]]);
recipes.addShaped(<ExtraUtilities:filing:1>, [[<ExtraUtilities:decorativeBlock1:8>, <IronChest:BlockIronChest:1>, <ExtraUtilities:decorativeBlock1:8>], [<ExtraUtilities:decorativeBlock1:8>, <IronChest:BlockIronChest:1>, <ExtraUtilities:decorativeBlock1:8>], [<ExtraUtilities:decorativeBlock1:8>, <IronChest:BlockIronChest:1>, <ExtraUtilities:decorativeBlock1:8>]]);
recipes.addShaped(<ExtraUtilities:extractor_base:6>, [[null, <ExtraUtilities:pipes>, null], [<ore:gemLapis>, <ImmersiveEngineering:material:11>, <ore:gemLapis>], [<minecraft:obsidian>, <ImmersiveEngineering:metalDevice2:6>, <minecraft:obsidian>]]);
recipes.addShaped(<ExtraUtilities:extractor_base>, [[null, <ExtraUtilities:pipes>, null], [<ore:dustRedstone>, <ImmersiveEngineering:material:11>, <ore:dustRedstone>], [<minecraft:obsidian>, <ProjRed|Expansion:projectred.expansion.machine2:1>, <minecraft:obsidian>]]);
recipes.addShaped(<ExtraUtilities:chandelier>, [[<ore:ingotGold>, <ore:gemDiamond>, <ore:ingotGold>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>], [<ore:cropNitorWart>, <ore:cropNitorWart>, <ore:cropNitorWart>]]);
recipes.addShaped(<ExtraUtilities:watering_can:3>, [[<Botania:manaResource:5>, <ExtraUtilities:mini-soul>.reuse(), <ore:eternalLifeEssence>], [<ore:runeSpringB>, <ExtraUtilities:watering_can:1>, <minecraft:potion:8225>], [<ore:eternalLifeEssence>, <Botania:specialFlower>.withTag({type: "agricarnation"}), <ore:eternalLifeEssence>]]);
recipes.addShaped(<ExtraUtilities:watering_can:1>, [[<ore:barsIron>, <ore:fertilizerOrganic>, <ore:ironRod>], [<ImmersiveEngineering:metalDevice2:5>, <ImmersiveEngineering:metalDevice2:7>, <ore:ironRod>]]);
recipes.addShaped(<ExtraUtilities:generator.64>, [[null, <ore:plateSteel>, null], [<ore:plateSteel>, <ThermalExpansion:Dynamo>, <ore:plateSteel>], [<ImmersiveEngineering:metalDevice:10>, <ExtraUtilities:generator.8>, <ImmersiveEngineering:metalDevice:10>]]);
recipes.addShaped(<ExtraUtilities:generator.8>, [[<ore:plateSteel>, <ore:gearStone>, <ore:plateSteel>], [<ore:plateConstantan>, <ExtraUtilities:generator>, <ore:plateConstantan>], [<ore:plateSteel>, <IC2:blockMachine:1>, <ore:plateSteel>]]);
recipes.addShaped(<ExtraUtilities:generator>, [[null, <ThermalExpansion:material:2>, null], [<ImmersiveEngineering:metalDevice2:5>, <minecraft:water_bucket>, <ImmersiveEngineering:metalDevice2:5>], [null, <minecraft:furnace>, null]]);
recipes.addShaped(<ExtraUtilities:enderThermicPump>, [[<ExtraUtilities:decorativeBlock1:1>, <ThermalDynamics:ThermalDynamics_0:1>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:1>, <ImmersiveEngineering:metalDevice2:6>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:11>, <ThermalExpansion:Frame:11>, <ExtraUtilities:decorativeBlock1:11>]]);
recipes.addShaped(<OpenBlocks:fan>, [[<academy-craft:ac_Item_windgenFan>], [<TConstruct:toughRod:2>], [<ore:slabStone>]]);
recipes.addShaped(<ExtraUtilities:generator.8>, [[<ore:plateAluminum>, <TConstruct:FurnaceSlab>, <ore:plateAluminum>], [<ImmersiveEngineering:metal:36>, <ExtraUtilities:generator>, <ImmersiveEngineering:metal:36>], [<ore:plateAluminum>, <TConstruct:FurnaceSlab>, <ore:plateAluminum>]]);
