recipes.remove(<ImmersiveEngineering:metal:32>);
recipes.remove(<ImmersiveEngineering:metal:30>);
recipes.remove(<ImmersiveEngineering:metal:33>);
recipes.remove(<ImmersiveEngineering:metal:36>);
recipes.remove(<ImmersiveEngineering:metal:38>);
recipes.remove(<ImmersiveEngineering:mold>);
recipes.remove(<ImmersiveEngineering:stoneDecoration:6>);
recipes.remove(<ImmersiveEngineering:woodenDevice:2>);
recipes.remove(<ImmersiveEngineering:woodenDevice:3>);
recipes.remove(<ImmersiveEngineering:woodenDevice:1>);
recipes.remove(<ImmersiveEngineering:clothDevice>);
recipes.remove(<ImmersiveEngineering:bullet>);
recipes.remove(<ImmersiveEngineering:tool:1>);
recipes.remove(<ImmersiveEngineering:material:15>);
recipes.remove(<ImmersiveEngineering:metalDecoration:11>);
recipes.remove(<ImmersiveEngineering:metalDecoration:3>);
recipes.remove(<ImmersiveEngineering:metalDecoration:1>);
recipes.remove(<ImmersiveEngineering:metalDecoration>);
recipes.remove(<ImmersiveEngineering:metalDevice:11>);
recipes.remove(<ImmersiveEngineering:metalDevice2:11>);
recipes.remove(<ImmersiveEngineering:metalDevice2:4>);
recipes.remove(<ImmersiveEngineering:metalDevice2:3>);
recipes.remove(<ImmersiveEngineering:metalDecoration:2>);
recipes.remove(<ImmersiveEngineering:metalDecoration:6>);
recipes.remove(<ImmersiveEngineering:metalDevice2:9>);
recipes.remove(<ImmersiveEngineering:metalDecoration:5>);
recipes.remove(<ImmersiveEngineering:metalDecoration:7>);
recipes.remove(<ImmersiveEngineering:material:12>);
recipes.remove(<ImmersiveEngineering:material:11>);
recipes.remove(<ImmersiveEngineering:metalDevice:10>);
recipes.remove(<ImmersiveEngineering:metalDevice:9>);
recipes.remove(<ImmersiveEngineering:metalDevice:7>);
recipes.remove(<ImmersiveEngineering:metalDevice:3>);
recipes.remove(<ImmersiveEngineering:metalDevice:1>);
recipes.remove(<ImmersiveEngineering:mold:1>);
recipes.remove(<ImmersiveEngineering:tool>);
recipes.remove(<ImmersiveEngineering:stoneDecoration:1>);
recipes.remove(<ImmersiveEngineering:stoneDecoration:2>);
recipes.remove(<ImmersiveEngineering:tool:3>);


recipes.removeShaped(<ImmersiveEngineering:stoneDecoration:6>, [[<ImmersiveEngineering:metal:38>, null, <ImmersiveEngineering:metal:38>], [null, <ImmersiveEngineering:stoneDecoration:2>, null], [<ImmersiveEngineering:metal:38>, null, <ImmersiveEngineering:metal:38>]]);
mods.immersiveengineering.MetalPress.removeRecipe(<academy-craft:ac_Item_constPlate>);


recipes.addShaped(<ImmersiveEngineering:metal:38>, [[<ImmersiveEngineering:tool>], [<ore:ingotSteel>], [<minecraft:anvil:2>]]);
recipes.addShaped(<ImmersiveEngineering:metal:38>, [[<ImmersiveEngineering:tool>], [<ore:ingotSteel>], [<minecraft:anvil:1>.giveBack(<minecraft:anvil:2>)]]);
recipes.addShaped(<ImmersiveEngineering:metal:38>, [[<ImmersiveEngineering:tool>], [<ore:ingotSteel>], [<minecraft:anvil>.giveBack(<minecraft:anvil:1>)]]);
recipes.addShaped(<ImmersiveEngineering:mold>, [[null, <ore:plateSteel>, null], [<ore:plateSteel>, <TConstruct:heavyPlate:16>, <ore:plateSteel>], [null, <ore:plateSteel>, null]]);
recipes.addShaped(<ImmersiveEngineering:stoneDecoration:6>, [[<ore:plateSteel>, null, <ore:plateSteel>], [null, <ImmersiveEngineering:stoneDecoration:2>, null], [<ore:plateSteel>, null, <ore:plateSteel>]]);
recipes.addShaped(<ImmersiveEngineering:material:2> * 4, [[<ImmersiveEngineering:woodenDevice:2>.giveBack(<TConstruct:toughRod:16>)]]);
recipes.addShaped(<ImmersiveEngineering:woodenDevice:3>, [[<ImmersiveEngineering:material:5>, <ImmersiveEngineering:material:5>, <ImmersiveEngineering:material:5>], [<ImmersiveEngineering:material:5>, <TConstruct:toughRod:16>, <ImmersiveEngineering:material:5>], [<ImmersiveEngineering:material:5>, <ImmersiveEngineering:material:5>, <ImmersiveEngineering:material:5>]]);
recipes.addShaped(<ImmersiveEngineering:woodenDevice:2>, [[null, <ImmersiveEngineering:material:2>, null], [<ImmersiveEngineering:material:2>, <TConstruct:toughRod:16>, <ImmersiveEngineering:material:2>], [null, <ImmersiveEngineering:material:2>, null]]);
recipes.addShaped(<ImmersiveEngineering:woodenDevice:1>, [[<ImmersiveEngineering:material:1>, <ImmersiveEngineering:material:1>, <ImmersiveEngineering:material:1>], [<ImmersiveEngineering:material:1>, <TConstruct:toughRod:16>, <ImmersiveEngineering:material:1>], [<ImmersiveEngineering:material:1>, <ImmersiveEngineering:material:1>, <ImmersiveEngineering:material:1>]]);
recipes.addShaped(<ImmersiveEngineering:clothDevice>, [[null, <ore:fabricHemp>, null], [<ore:fabricHemp>, <ImmersiveEngineering:metalDecoration:2>, <ore:fabricHemp>], [null, <ore:slabTreatedWood>, null]]);
recipes.addShaped(<ImmersiveEngineering:bullet> * 6, [[<ore:ingotCopper>, null], [null, <ore:ingotCopper>]]);
recipes.addShaped(<ImmersiveEngineering:tool:1>, [[null, <ImmersiveEngineering:metal:38>, null], [<ImmersiveEngineering:metal:38>, <ore:ingotIron>, <ore:treatedStick>], [null, <ore:treatedStick>, null]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:3> * 24, [[null, null, <ore:fenceSteel>], [null, <TConstruct:toughBinding:16>, <TConstruct:toughRod:16>], [<ore:fenceSteel>, <TConstruct:toughRod:16>, <ore:fenceSteel>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:1>, [[<ImmersiveEngineering:metalDecoration:11>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:11>, [[<ore:slabTreatedWood>.reuse()], [<ImmersiveEngineering:metalDecoration:1>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:1> * 32, [[<ore:fenceSteel>, <TConstruct:toughRod:16>, <ore:fenceSteel>], [<TConstruct:toughRod:16>, <TConstruct:toughBinding:16>, <TConstruct:toughRod:16>], [<ore:fenceSteel>, <TConstruct:toughRod:16>, <ore:fenceSteel>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration> * 16, [[<TConstruct:toughRod:16>, <ImmersiveEngineering:material:15>, <TConstruct:toughRod:16>], [<TConstruct:toughRod:16>, <ImmersiveEngineering:material:15>, <TConstruct:toughRod:16>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice:11>, [[<minecraft:leather>, <minecraft:leather>, <minecraft:leather>], [<ore:ingotIron>, <ImmersiveEngineering:material:11>, <ore:ingotIron>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice2:11>, [[<ImmersiveEngineering:metalDevice2:5>, null], [<ImmersiveEngineering:metalDevice2:5>, <ImmersiveEngineering:metalDevice:2>], [<ImmersiveEngineering:metalDevice:12>, <ImmersiveEngineering:material:12>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice2:4>, [[<ore:plateSteel>, <ore:plateSteel>, null], [<ore:paneGlassColorless>, <ImmersiveEngineering:storage:9>, <ore:plateSteel>], [<ore:ingotSteel>, <ImmersiveEngineering:material:12>, <ImmersiveEngineering:coil:1>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice2:3>, [[<ore:treatedStick>, <ImmersiveEngineering:woodenDecoration:2>, <ore:treatedStick>], [<ore:paneGlassColorless>, <ImmersiveEngineering:coil>, <ore:paneGlassColorless>], [<ore:treatedStick>, <ImmersiveEngineering:woodenDecoration:2>, <ore:treatedStick>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:2>, [[<ore:treatedStick>, <ore:plateSteel>, <ore:treatedStick>], [<ore:paneGlassColorless>, <ImmersiveEngineering:fluidContainers:4>, <ore:paneGlassColorless>], [<ore:treatedStick>, <ore:plateSteel>, <ore:treatedStick>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:6>, [[<ore:plateSteel>, <ImmersiveEngineering:storage:8>, <ore:plateSteel>], [<ImmersiveEngineering:storage:8>, <ImmersiveEngineering:material:11>, <ImmersiveEngineering:storage:8>], [<ore:plateSteel>, <ImmersiveEngineering:storage:8>, <ore:plateSteel>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice2:9>, [[<ImmersiveEngineering:metalDevice:2>, null, <ImmersiveEngineering:metalDevice:2>], [<ore:ingotElectrum>, <ImmersiveEngineering:metalDevice2>, <ore:ingotElectrum>], [<ore:plateSteel>, <ore:plateSteel>, <ore:plateSteel>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:7>, [[<ore:plateIron>, <ore:gearIron>, <ore:plateIron>], [<ImmersiveEngineering:coil>, <ImmersiveEngineering:material:11>, <ImmersiveEngineering:coil>], [<ore:plateIron>, <ore:gearIron>, <ore:plateIron>]]);
recipes.addShaped(<ImmersiveEngineering:metalDecoration:5>, [[<ore:plateSteel>, <ore:gearInvar>, <ore:plateSteel>], [<ImmersiveEngineering:coil:2>, <ImmersiveEngineering:material:12>, <ImmersiveEngineering:coil:2>], [<ore:plateSteel>, <ore:gearInvar>, <ore:plateSteel>]]);
recipes.addShaped(<ImmersiveEngineering:material:12>, [[<ore:ingotSteel>, <ImmersiveEngineering:coil:1>, <ore:ingotSteel>], [<ore:gearInvar>, <TConstruct:toolRod:16>, <ore:gearInvar>], [<ore:ingotSteel>, <ImmersiveEngineering:coil:1>, <ore:ingotSteel>]]);
recipes.addShaped(<ImmersiveEngineering:material:11>, [[<ore:ingotIron>, <ImmersiveEngineering:coil>, <ore:ingotIron>], [<ore:gearIron>, <TConstruct:toolRod:2>, <ore:gearIron>], [<ore:ingotIron>, <ImmersiveEngineering:coil>, <ore:ingotIron>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice:10>, [[<ore:plateSteel>, <ImmersiveEngineering:storage:9>, <ore:plateSteel>], [<ore:plateConstantan>, <ore:plateAluminum>, <ore:plateConstantan>], [<ore:ingotSteel>, <ore:ingotSteel>, <ore:ingotSteel>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice:9>, [[<ore:plateSteel>, <ImmersiveEngineering:storage:8>, <ImmersiveEngineering:storage:8>], [<ore:gearIron>, <TConstruct:toughRod:2>, <TConstruct:toughRod:2>], [<ore:plateSteel>, <ImmersiveEngineering:storage:8>, <ImmersiveEngineering:storage:8>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice:7>, [[<ore:plateSteel>, <ore:blockElectrum>, <ore:plateSteel>], [<ore:plateSteel>, <ThermalExpansion:Frame:9>, <ore:plateSteel>], [<ore:plankTreatedWood>, <ImmersiveEngineering:storage:10>, <ore:plankTreatedWood>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice:3>, [[<ore:plateSteel>, <ore:ingotElectrum>, <ore:plateSteel>], [<ore:plateSteel>, <ThermalExpansion:Frame:7>, <ore:plateSteel>], [<ore:plankTreatedWood>, <ImmersiveEngineering:storage:9>, <ore:plankTreatedWood>]]);
recipes.addShaped(<ImmersiveEngineering:metalDevice:1>, [[<ore:plateSteel>, <ore:ingotGold>, <ore:plateSteel>], [<ore:plateSteel>, <ThermalExpansion:Frame:5>, <ore:plateSteel>], [<ore:plankTreatedWood>, <ImmersiveEngineering:storage:8>, <ore:plankTreatedWood>]]);
recipes.addShaped(<ImmersiveEngineering:metal:15>, [[<ImmersiveEngineering:tool>], [<ore:ingotConstantan>], [<minecraft:anvil>.reuse()]]);
recipes.addShaped(<ImmersiveEngineering:metal:32>, [[<ImmersiveEngineering:tool>], [<ore:ingotAluminum>], [<minecraft:anvil>.reuse()]]);
recipes.addShaped(<ImmersiveEngineering:metal:30>, [[<ImmersiveEngineering:tool>], [<ore:ingotIron>], [<minecraft:anvil>.reuse()]]);
recipes.addShaped(<ImmersiveEngineering:material:3> * 3, [[<BiomesOPlenty:mudball>, <BiomesOPlenty:mudball>, <BiomesOPlenty:mudball>], [<BiomesOPlenty:mudball>, <claybucket:claybucket:1>.giveBack(<claybucket:claybucket>), <BiomesOPlenty:mudball>], [<BiomesOPlenty:mudball>, <BiomesOPlenty:mudball>, <BiomesOPlenty:mudball>]]);
recipes.addShaped(<ImmersiveEngineering:tool>, [[null, <ore:ingotIron>, <ImmersiveEngineering:material:3>], [null, <ore:stickWood>, <ore:ingotIron>], [<ore:stickWood>, null, <ImmersiveEngineering:tool:3>.reuse()]]);
recipes.addShaped(<ImmersiveEngineering:stoneDecoration:1> * 2, [[<TConstruct:materials:37>, <ore:itemClay>, <TConstruct:materials:37>], [<ore:itemClay>, <TConstruct:Smeltery:2>, <ore:itemClay>], [<TConstruct:materials:37>, <ore:itemClay>, <TConstruct:materials:37>]]);
recipes.addShaped(<ImmersiveEngineering:stoneDecoration:2> * 2, [[<ore:ingotBrickNether>, <ore:itemClay>, <minecraft:netherbrick>], [<ore:itemClay>, <TConstruct:Smeltery:2>, <ore:itemClay>], [<ore:ingotBrickNether>, <ore:itemClay>, <ore:ingotBrickNether>]]);
recipes.addShaped(<ImmersiveEngineering:mold:1>, [[<ForgeMicroblock:sawDiamond>], [<EnderIO:itemMachinePart:1>], [<TConstruct:heavyPlate:16>]]);
recipes.addShapeless(<ImmersiveEngineering:tool:3>, [<ImmersiveEngineering:stoneDecoration:2>, <ore:seedIndustrialHemp>, <ImmersiveEngineering:stoneDecoration:1>]);
