recipes.remove(<TConstruct:CraftingStation>);
recipes.remove(<TConstruct:ToolStationBlock>);
recipes.remove(<TConstruct:ToolStationBlock:1>);
recipes.remove(<TConstruct:ToolStationBlock:3>);
recipes.remove(<TConstruct:ToolStationBlock:2>);
recipes.remove(<TConstruct:ToolStationBlock:5>);
recipes.remove(<TConstruct:ToolStationBlock:4>);
recipes.remove(<TConstruct:ToolStationBlock:12>);
recipes.remove(<TConstruct:ToolStationBlock:13>);
recipes.remove(<TConstruct:ToolStationBlock:11>);
recipes.remove(<TConstruct:ToolStationBlock:10>);
recipes.remove(<TConstruct:ToolForgeBlock>);
recipes.remove(<TConstruct:ToolForgeBlock:1>);
recipes.remove(<TConstruct:ToolForgeBlock:2>);
recipes.remove(<TConstruct:ToolForgeBlock:3>);
recipes.remove(<TConstruct:ToolForgeBlock:4>);
recipes.remove(<TConstruct:ToolForgeBlock:5>);
recipes.remove(<TConstruct:ToolForgeBlock:6>);
recipes.remove(<TConstruct:ToolForgeBlock:7>);
recipes.remove(<TConstruct:ToolForgeBlock:8>);
recipes.remove(<TConstruct:ToolForgeBlock:9>);
recipes.remove(<TConstruct:ToolForgeBlock:10>);
recipes.remove(<TConstruct:ToolForgeBlock:11>);
recipes.remove(<TConstruct:ToolForgeBlock:12>);
recipes.remove(<TConstruct:ToolForgeBlock:13>);
recipes.remove(<TConstruct:ToolForgeBlock:14>);
recipes.remove(<TConstruct:ToolForgeBlock:15>);
recipes.remove(<TConstruct:FurnaceSlab>);
recipes.remove(<TConstruct:CraftingSlab:5>);
recipes.remove(<TConstruct:explosive.slime:2>);
recipes.remove(<TConstruct:explosive.slime>);
recipes.remove(<TConstruct:CraftedSoil:6>);
recipes.remove(<TConstruct:LavaTankNether>);
recipes.remove(<TConstruct:LavaTank>);
recipes.remove(<TConstruct:SearedBlockNether:2>);
recipes.remove(<TConstruct:SearedBlock:2>);
recipes.remove(<TConstruct:SmelteryNether:2>);
recipes.remove(<TConstruct:SmelteryNether:1>);
recipes.remove(<TConstruct:SmelteryNether>);
recipes.remove(<TConstruct:Smeltery:1>);
recipes.remove(<TConstruct:Smeltery:2>);
recipes.remove(<TConstruct:Smeltery>);
recipes.remove(<TConstruct:materials:26>);
recipes.remove(<TConstruct:materials:25>);
recipes.remove(<TConstruct:materials:7>);
recipes.remove(<TConstruct:heartCanister:6>);
recipes.remove(<TConstruct:heartCanister:4>);
recipes.remove(<TConstruct:heartCanister:2>);
recipes.remove(<TConstruct:heartCanister>);

recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:13>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:12>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:11>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:10>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:9>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:8>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:7>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:6>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:5>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:4>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:3>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:2>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock:1>]);
recipes.addShapeless(<TConstruct:CraftingSlab:5>, [<TConstruct:ToolForgeBlock>]);


recipes.addShaped(<TConstruct:FurnaceSlab>, [[<minecraft:stone_slab:3>, <minecraft:stone_slab:3>], [<minecraft:stone_slab:3>, <minecraft:stone_slab:3>]]);
recipes.addShaped(<TConstruct:blankPattern> * 4, [[<BiomesOPlenty:logs3:2>, <minecraft:stick>], [<minecraft:stick>, <BiomesOPlenty:logs3:2>]]);
recipes.addShaped(<TConstruct:CraftingStation>, [[<minecraft:stick>, <ore:crafterWood>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<TConstruct:ToolStationBlock>, [[<TConstruct:blankPattern>, <TConstruct:blankPattern>, <TConstruct:blankPattern>], [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>], [<ore:logWood>, <TConstruct:CraftingStation>, <ore:logWood>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:1>, [[<minecraft:stone>, <TConstruct:toughBinding>, <minecraft:stone>], [<minecraft:log>, <minecraft:stone>, <minecraft:log>], [<minecraft:log>, <TConstruct:CraftingStation>, <minecraft:log>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:1>, [[<minecraft:stone>, <TConstruct:toughBinding>, <minecraft:stone>], [<BiomesOPlenty:logs3:2>, <minecraft:stone>, <BiomesOPlenty:logs3:2>], [<BiomesOPlenty:logs3:2>, <TConstruct:CraftingStation>, <BiomesOPlenty:logs3:2>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:2>, [[<minecraft:stone>, <TConstruct:toughBinding>, <minecraft:stone>], [<minecraft:log:1>, <minecraft:stone>, <minecraft:log:1>], [<minecraft:log:1>, <TConstruct:CraftingStation>, <minecraft:log:1>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:3>, [[<minecraft:stone>, <TConstruct:toughBinding>, <minecraft:stone>], [<minecraft:log:2>, <minecraft:stone>, <minecraft:log:2>], [<minecraft:log:2>, <TConstruct:CraftingStation>, <minecraft:log:2>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:4>, [[<minecraft:stone>, <TConstruct:toughBinding>, <minecraft:stone>], [<minecraft:log:3>, <minecraft:stone>, <minecraft:log:3>], [<minecraft:log:3>, <TConstruct:CraftingStation>,<minecraft:log:3>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:13>, [[null, <minecraft:stick>, null], [<minecraft:log:3>, <TConstruct:blankPattern>, <minecraft:log:3>], [<minecraft:log:3>, <TConstruct:CraftingStation>, <minecraft:log:3>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:12>, [[null, <minecraft:stick>, null], [<minecraft:log:2>, <TConstruct:blankPattern>, <minecraft:log:2>], [<minecraft:log:2>, <TConstruct:CraftingStation>, <minecraft:log:2>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:11>, [[null, <minecraft:stick>, null], [<minecraft:log:1>, <TConstruct:blankPattern>, <minecraft:log:1>], [<minecraft:log:1>, <TConstruct:CraftingStation>, <minecraft:log:1>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:10>, [[null, <minecraft:stick>, null], [<BiomesOPlenty:logs3:2>, <TConstruct:blankPattern>, <BiomesOPlenty:logs3:2>], [<BiomesOPlenty:logs3:2>, <TConstruct:CraftingStation>, <BiomesOPlenty:logs3:2>]]);
recipes.addShaped(<TConstruct:ToolStationBlock:10>, [[null, <minecraft:stick>, null], [<minecraft:log>, <TConstruct:blankPattern>, <minecraft:log>], [<minecraft:log>, <TConstruct:CraftingStation>, <minecraft:log>]]);
recipes.addShaped(<TConstruct:LavaTankNether>, [[<TConstruct:materials:37>, <BiomesOPlenty:mudball>, <TConstruct:materials:37>], [<BiomesOPlenty:mudball>, <TConstruct:LavaTankNether:2>, <BiomesOPlenty:mudball>], [<TConstruct:materials:37>, <BiomesOPlenty:mudball>, <TConstruct:materials:37>]]);
recipes.addShaped(<TConstruct:LavaTank>, [[<TConstruct:materials:2>, <minecraft:clay_ball>, <TConstruct:materials:2>], [<minecraft:clay_ball>, <TConstruct:LavaTank:2>, <minecraft:clay_ball>], [<TConstruct:materials:2>, <minecraft:clay_ball>, <TConstruct:materials:2>]]);
recipes.addShaped(<TConstruct:SearedBlockNether:2>, [[<TConstruct:materials:37>, <TConstruct:CastingChannel>, <TConstruct:materials:37>], [<TConstruct:materials:37>, null, <TConstruct:materials:37>], [<TConstruct:materials:37>, <minecraft:cauldron>, <TConstruct:materials:37>]]);
recipes.addShaped(<TConstruct:SearedBlock:2>, [[<TConstruct:materials:2>, <TConstruct:CastingChannel>, <TConstruct:materials:2>], [<TConstruct:materials:2>, null, <TConstruct:materials:2>], [<TConstruct:materials:2>, <minecraft:cauldron>, <TConstruct:materials:2>]]);
recipes.addShaped(<TConstruct:SmelteryNether:1>, [[<TConstruct:materials:37>, <BiomesOPlenty:mudball>, <TConstruct:materials:37>], [<BiomesOPlenty:mudball>, <TConstruct:CastingChannel>, <BiomesOPlenty:mudball>], [<TConstruct:materials:37>, <BiomesOPlenty:mudball>, <TConstruct:materials:37>]]);
recipes.addShaped(<TConstruct:Smeltery:1>, [[<TConstruct:materials:2>, <minecraft:clay_ball>, <TConstruct:materials:2>], [<minecraft:clay_ball>, <TConstruct:CastingChannel>, <minecraft:clay_ball>], [<TConstruct:materials:2>, <minecraft:clay_ball>, <TConstruct:materials:2>]]);
recipes.addShaped(<TConstruct:SmelteryNether>, [[<TConstruct:materials:37>, <minecraft:hopper>, <TConstruct:materials:37>], [<minecraft:iron_bars>, <IronChest:BlockIronChest:3>, <BiomesOPlenty:mudball>], [<TConstruct:materials:37>, <BiomesOPlenty:mudball>, <TConstruct:materials:37>]]);
recipes.addShaped(<TConstruct:Smeltery>, [[<TConstruct:materials:2>, <minecraft:hopper>, <TConstruct:materials:2>], [<minecraft:iron_bars>, <IronChest:BlockIronChest>, <minecraft:clay_ball>], [<TConstruct:materials:2>, <minecraft:clay_ball>, <TConstruct:materials:2>]]);
recipes.addShaped(<TConstruct:Smeltery:2>, [[<minecraft:clay_ball>, <TConstruct:materials:2>, <minecraft:clay_ball>], [<TConstruct:materials:2>, <minecraft:clay_ball>, <TConstruct:materials:2>], [<minecraft:clay_ball>, <TConstruct:materials:2>, <minecraft:clay_ball>]]);
recipes.addShaped(<TConstruct:SmelteryNether:2>, [[<BiomesOPlenty:mudball>, <TConstruct:materials:37>, <BiomesOPlenty:mudball>], [<TConstruct:materials:37>, <BiomesOPlenty:mudball>, <TConstruct:materials:37>], [<BiomesOPlenty:mudball>, <TConstruct:materials:37>, <BiomesOPlenty:mudball>]]);
recipes.addShaped(<TConstruct:CraftedSoil:6> * 2, [[<minecraft:clay_ball>, <BiomesOPlenty:mud>], [<minecraft:gravel>, null]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:8>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockBronze>, <TConstruct:ToolStationBlock>, <ore:blockBronze>], [<ore:blockBronze>, null, <ore:blockBronze>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:9>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockTin>, <TConstruct:ToolStationBlock>, <ore:blockTin>], [<ore:blockTin>, null, <ore:blockTin>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:10>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockAluminum>, <TConstruct:ToolStationBlock>, <ore:blockAluminum>], [<ore:blockAluminum>, null, <ore:blockAluminum>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:12>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockAlumite>, <TConstruct:ToolStationBlock>, <ore:blockAlumite>], [<ore:blockAlumite>, null, <ore:blockAlumite>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:13>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockSteel>, <TConstruct:ToolStationBlock>, <ore:blockSteel>], [<ore:blockSteel>, null, <ore:blockSteel>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:11>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockAluminumBrass>, <TConstruct:ToolStationBlock>, <ore:blockAluminumBrass>], [<ore:blockAluminumBrass>, null, <ore:blockAluminumBrass>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:7>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockCopper>, <TConstruct:ToolStationBlock>, <ore:blockCopper>], [<ore:blockCopper>, null, <ore:blockCopper>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:6>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockManyullyn>, <TConstruct:ToolStationBlock>, <ore:blockManyullyn>], [<ore:blockManyullyn>, null, <ore:blockManyullyn>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:5>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockArdite>, <TConstruct:ToolStationBlock>, <ore:blockArdite>], [<ore:blockArdite>, null, <ore:blockArdite>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:4>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockCobalt>, <TConstruct:ToolStationBlock>, <ore:blockCobalt>], [<ore:blockCobalt>, null, <ore:blockCobalt>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:3>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockEmerald>, <TConstruct:ToolStationBlock>, <ore:blockEmerald>], [<ore:blockEmerald>, null, <ore:blockEmerald>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:2>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockDiamond>, <TConstruct:ToolStationBlock>, <ore:blockDiamond>], [<ore:blockDiamond>, null, <ore:blockDiamond>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock:1>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockGold>, <TConstruct:ToolStationBlock>, <ore:blockGold>], [<ore:blockGold>, null, <ore:blockGold>]]);
recipes.addShaped(<TConstruct:ToolForgeBlock>, [[<TConstruct:Smeltery:2>, <minecraft:anvil>, <TConstruct:Smeltery:2>], [<ore:blockIron>, <TConstruct:ToolStationBlock>, <ore:blockIron>], [<ore:blockIron>, null, <ore:blockIron>]]);
